modLoader = "javafml"
loaderVersion = "[36,)"
license = "GPL-3.0"
issueTrackerURL = "https://github.com/GrowthcraftCE/Growthcraft-1.16/issues"

[[mods]]
modId = "growthcraft"
version = "6.1.0"
displayName = "Growthcraft"
updateJSONURL = "https://raw.githubusercontent.com/GrowthcraftCE/Growthcraft-Updates/master/growthcraft-versions.json"
displayURL = "https://github.com/GrowthcraftCE/Growthcraft-1.16/wiki"
logoFile = "growthcraft_core_logo.png"
credits = "Thanks to Gwafu for starting a great mod. And the Growthcraft CE Development for continuing the work."
authors = "Alatyami"
description = '''
  Growthcraft is a realistic and immersive Forge mod that adds various new elements to the game of Minecraft.
            '''

[[dependencies.growthcraft]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.growthcraft]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"

[[mods]]
modId = "growthcraft_cellar"
version = "6.1.0"
displayName = "Growthcraft Cellar"
logoFile = "growthcraft_cellar_logo.png"
description = '''
  Growthcraft Cellar adds brewing, winery, grapes, and hops for being made into consumable drinks.
'''

[[dependencies.growthcraft_cellar]]
modId = "growthcraft"
mandatory = true
versionRange = "[6,)"
ordering = "AFTER"
side = "BOTH"


[[mods]]
modId = "growthcraft_apiary"
version = "6.1.0"
displayName = "Growthcraft Apiary"
logoFile = "growthcraft_bees_logo.png"
description = '''
  Growthcraft Bees adds honey generation and processing.
'''

[[dependencies.growthcraft_apiary]]
modId = "growthcraft"
mandatory = true
versionRange = "[6,)"
ordering = "AFTER"
side = "BOTH"

[[mods]]
modId = "growthcraft_apples"
version = "6.1.0"
displayName = "Growthcraft Apples"
logoFile = "growthcraft_apples_logo.png"
description = '''
  Growthcraft Apples adds Apple Trees.
'''

[[dependencies.growthcraft_apples]]
modId = "growthcraft"
mandatory = true
versionRange = "[6,)"
ordering = "AFTER"
side = "BOTH"

[[mods]]
modId = "growthcraft_bamboo"
version = "6.1.0"
displayName = "Growthcraft Bamboo"
logoFile = "growthcraft_bamboo_logo.png"
description = '''
  Growthcraft Bamboo adds a custom Bamboo Tree and blocks.
'''

[[dependencies.growthcraft_bamboo]]
modId = "growthcraft"
mandatory = true
versionRange = "[6,)"
ordering = "AFTER"
side = "BOTH"

[[mods]]
modId = "growthcraft_milk"
version = "6.1.0"
displayName = "Growthcraft Milk"
logoFile = "growthcraft_milk_logo.png"
description = '''
  Growthcraft Milk adds more usages for milk to Minecraft.
'''

[[dependencies.growthcraft_milk]]
modId = "growthcraft"
mandatory = true
versionRange = "[6,)"
ordering = "AFTER"
side = "BOTH"

[[mods]]
modId = "growthcraft_rice"
version = "6.1.0"
displayName = "Growthcraft Rice"
logoFile = "growthcraft_rice_logo.png"
description = '''
  Growthcraft Rice adds a rice to Minecraft, along with rice based drinks and water based crops.
'''

[[dependencies.growthcraft_rice]]
modId = "growthcraft"
mandatory = true
versionRange = "[6,)"
ordering = "AFTER"
side = "BOTH"

